default_platform(:android)

platform :android do
  desc "Deploy to Google Play Internal track"
  lane :deploy_internal do
    gradle(task: "bundleRelease")

    upload_to_play_store(
      track: 'internal',
      json_key: './fastlane/service_account_key.json',
      package_name: 'com.notesnest',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Deploy to Google Play Production track with rollout"
  lane :deploy_production do
    gradle(task: "bundleRelease")

    upload_to_play_store(
      track: 'production',
      rollout: 0.1, # 10% rollout
      json_key: './fastlane/service_account_key.json',
      package_name: 'com.notesnest',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
