name: Deploy to Internal

on:
  workflow_run:
    workflows: ["Flutter Build"]
    types:
      - completed

jobs:
  deploy_internal:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: 🚀 Deploy to Internal Track
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Download artifact from triggering workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Flutter Build
          name: flutter-aab
          path: build/app/outputs/bundle/release/
          run_id: ${{ github.event.workflow_run.id }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Create local.properties
        run: echo "flutter.sdk=$(flutter sdk-path)" > android/local.properties

      - name: Decode google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Decode strings.xml
        run: |
          echo "${{ secrets.STRINGS_XML_BASE64 }}" | base64 --decode > android/app/src/main/res/values/strings.xml

      - name: Decode keystore
        run: |
          mkdir -p android/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/keystore/release-key.jks

      - name: Create keystore.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/keystore.properties
          echo "storeFile=keystore/release-key.jks" >> android/keystore.properties

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane and Plugins
        run: |
          gem install fastlane
          fastlane add_plugin versioning_android
        working-directory: android

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: android

      - name: Run Fastlane Internal Deployment
        env:
          SUPPLY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_BASE64 }}
        run: |
          mkdir -p fastlane
          echo "$SUPPLY_JSON_KEY" | base64 --decode > fastlane/service_account_key.json
          fastlane deploy_internal
        working-directory: android
