name: Flutter CI/CD

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Specify the version of Flutter you want to use

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests
      - name: Run Flutter tests
        run: flutter test

      # Build the APK (For Android)
      # - name: Build APK
      #   run: flutter build apk --release

      # # Upload build artifacts (Optional)
      # - name: Upload APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: flutter-apk
      #     path: build/app/outputs/flutter-apk/app-release.apk
