name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      # Restore google-services.json from GitHub Secret
      - name: Decode google-services.json from secret
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > android/app/google-services.json

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the APK (For Android)
      - name: Build APK
        run: flutter build apk --release

      # Upload build artifacts (Optional)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Optional: Clean up sensitive files
      - name: Clean up secrets
        run: rm android/app/google-services.json