name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Decode google-services.json from secret
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Decode strings.xml
        run: |
          echo "${{ secrets.STRINGS_XML_BASE64 }}" | base64 --decode > android/app/src/main/res/values/strings.xml

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Install dependencies
        run: flutter pub get

      - name: Build App Bundle (.aab)
        run: flutter build appbundle --release

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: flutter-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Clean up secrets
        run: |
          rm android/app/google-services.json
          rm android/app/src/main/res/values/strings.xml

  deploy_internal:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download built AAB
        uses: actions/download-artifact@v4
        with:
          name: flutter-aab
          path: build/app/outputs/bundle/release/

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Create local.properties
        run: echo "flutter.sdk=$(flutter sdk-path)" > android/local.properties

      - name: Install Fastlane
        run: gem install fastlane
        working-directory: android

      - name: Ensure gradlew is executable
        run: chmod +x gradlew
        working-directory: android

      - name: Deploy to Internal Track
        env:
          SUPPLY_JSON_KEY: ${{ secrets.SUPPLY_JSON_KEY }}
        run: |
          mkdir -p fastlane
          echo "${SUPPLY_JSON_KEY}" > fastlane/service_account_key.json
          fastlane deploy_internal
        working-directory: android

  # deploy_production:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Download built AAB
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: flutter-aab
  #         path: build/app/outputs/bundle/release/

  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.1

  #     - name: Create local.properties
  #       run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

  #     - name: Install Fastlane
  #       run: gem install fastlane
  #       working-directory: android

  #     - name: Ensure gradlew is executable
  #       run: chmod +x gradlew
  #       working-directory: android

  #     - name: Deploy to Production Track
  #       env:
  #         SUPPLY_JSON_KEY: ${{ secrets.SUPPLY_JSON_KEY }}
  #       run: |
  #         mkdir -p fastlane
  #         echo "${SUPPLY_JSON_KEY}" > fastlane/service_account_key.json
  #         fastlane deploy_production
  #       working-directory: android
